version: '2'
services:
  graphite:
    image: sitespeedio/graphite
    ports:
      - "9876:80"
      - "2003:2003"
    volumes:
      - ./storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    #build: /Users/ruben/fromsource/kafka-docker/.
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  twitter:
     build: .
     environment:
       KAFKA: kafka:9092
       TWITTERCONSUMERKEY: ${TWITTERCONSUMERKEY}
       TWITTERCONSUMERSECRET: ${TWITTERCONSUMERSECRET}
       TWITTERACCESSTOKEN: ${TWITTERACCESSTOKEN}
       TWITTERACCESSTOKENSECRET: ${TWITTERACCESSTOKENSECRET}
     links:
       - kafka
       - graphite

